pipeline:
  verify:
    image: maven:3.6.1-jdk-8
    commands:
      - mvn clean verify -Dwebdriver.remote.url=http://selenium-hub:4444/wd/hub

services:
  selenium-hub:
    image: selenium/hub:3.141.59-oxygen
    container_name: selenium-hub

  chrome:
    image: selenium/node-chrome:3.141.59-oxygen
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444